#!/usr/bin/env bash
# Installs ngnix, listens on port 80, modifies the default web file

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'y' | ufw enable
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
