#!/usr/bin/env bash
# generates a mysql dump of all databases in MySQL and compresses it to a tar

mysqldump --all-databases -uroot -p"$1"  > backup.sql

tar -czvf "$(date "+%d-%m-%Y").tar.gz" backup.sql
