#!/usr/bin/env bash
# Resets the server to work port 80 on nginx by modifying the sites-enabled
sed -i "s/^\tlisten 8080 default_server;/\tlisten 80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s/^\tlisten \[::\]:8080 default_server ipv6only=on;/\tlisten \[::\]:80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s| ipv6only=on||" /etc/nginx/sites-enabled/default
service nginx restart
