#!/usr/bin/env bash
# Isnt it ust task 0 with less steps but i already have less steps
sed -i "s/8080 default/80 default" /etc/sites-enabled/default
service nginx restart
kill -9 "$(cat /run/nginx.pid)"
