#!/usr/bin/env bash
# while and if-else statements part2
i="0"
while [ $i -lt 20 ]
do
	case $i in
		3) echo "bad luck from China";; 
		8) echo "bad luck from Japan";;
		16) echo "bad luck from Japan";;
		*) echo "Best School"
	esac
i=$((i+1))
done
