#!/usr/bin/env bash
# runs nginx as nginx user at port 8080
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache2
sudo -u nginx service nginx restart
