#!/usr/bin/env bash
# shorter Script for starting nginx as nginx user
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
pkill -9 apache
su nginx -c "service nginx restart"
